version: "3.9"
services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    depends_on:
      - db
volumes:
  pgdbdata: null